name: Metrics
on:
  # Automatisch alle 24 Stunden aktualisieren
  schedule: [{cron: "0 0 * * *"}]
  # Erlaubt manuelles Starten Ã¼ber den "Actions" Tab
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General display
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Design-Optionen
          user: magenbrot
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Berlin
          
          # Plugins (Beispiel: Top Languages)
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          
          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
